name: Release Plugins

on:
  push:
    branches: [ master ]

jobs:

  release:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: test python 2-3
        run: | 
          sudo apt install 2to3
          python -m venv dist/working/env
          which 2to3

      - name: Compile
        run: |
          make dist
          
      - name: check outputs
        run: |
          ls -R
          cp ladybug-blender-*.zip ladybug-blender.zip

      - name: release
        run: |
          run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}